### PR TITLE
Fix add recipe with tag bug

### LINKED ISSUE #113: [Bug] Random errors are thrown
image

Random errors are being thrown when the input is accurate and the tag for DURING_COOKING does not show.

### PR DESCRIPTION
**Pull request by kaijie0102**
fixes #113

### CODE REVIEW

File: src/main/java/essenmakanan/command/AddRecipeCommand.java [hunk 1]
```diff
@@ -22,16 +22,20 @@ public AddRecipeCommand(String toAdd, RecipeList recipes) {
...
             }
-        } else if (toAdd.contains("r/") && toAdd.contains("s/") && toAdd.contains("t/")) {
+        } else if ((toAdd.contains("r/") && toAdd.contains("s/") && toAdd.contains("i/"))) {
             // only title and steps are available
-            this.addWithTitleStepsTags();
+            try {
+                this.addWithTitleAndStepsAndIngredients();
+            } catch (EssenFormatException e) {
+                e.handleException();
+            }
```
Comment (charkty) [inline src/main/java/essenmakanan/command/AddRecipeCommand.java:38]: Nice handling of exception, helps to fix the bug
