### PR TITLE
Handle invalid ingredient adding, use ingredient command

### LINKED ISSUE #234: [Bug] Ingredient - Do not allow to "use up" using add negative value

### LINKED ISSUE #236: [Bug] Ingredient when left empty crashes the app
i/egg,,kg

### PR DESCRIPTION
**Pull request by kaijie0102**
fixes #236 
fixes #234

### CODE REVIEW

File: src/main/java/essenmakanan/command/UseIngredientCommand.java [hunk 1]
```diff
@@ -0,0 +1,50 @@
...
+                    newIngredient.setQuantity(-newIngredient.getQuantity());
+                    this.ingredients.updateIngredient(newIngredient);
+                } else {
+                    // do nothing
+                    Ui.printIngredientDoesNotExist(newIngredient.getName());
+                }
+            } catch (EssenFormatException e) {
+                e.handleException();
+            }
+        }
```
Comment (StanleyW00) [inline src/main/java/essenmakanan/command/UseIngredientCommand.java:48]: Should this part be abstracted so it is not too nested?

**Review by StanleyW00 — CHANGES_REQUESTED** [review]
There is one part that should be abstracted. Other than that, LGTM.

File: src/main/java/essenmakanan/command/UseIngredientCommand.java [hunk 2]
```diff
@@ -0,0 +1,54 @@
...
+    @Override
+    public void executeCommand() {
+        String[] allIngredients = toUse.split("i/");
+
+        for (String ingredient : allIngredients) {
+            if (ingredient.isEmpty()) {
+                continue;
+            }
+
+            updateIngredientQuantity(ingredient);
```
Comment (charkty) [inline src/main/java/essenmakanan/command/UseIngredientCommand.java:28]: Would it be better to do if(!ingredient.isEmpty()){...} so that everything is handled within the if statement?

File: src/main/java/essenmakanan/command/UseIngredientCommand.java [hunk 3]
```diff
@@ -0,0 +1,54 @@
...
+
+            if (newIngredient.getQuantity() < 0) {
+                Ui.printNegativeIngredientQuantity();
+                return;
+            }
+
+            if (this.ingredients.exist(newIngredient.getName())) {
+                // if ingredient already exists, update the quantity by changing quantity to negative
+                newIngredient.setQuantity(-newIngredient.getQuantity());
+                this.ingredients.updateIngredient(newIngredient);
```
Comment (charkty) [inline src/main/java/essenmakanan/command/UseIngredientCommand.java:45]: I like the consistency in this if statement where Single Level of Abstraction Principle is used!

File: src/main/java/essenmakanan/ui/Ui.java [hunk 4]
```diff
@@ -220,4 +220,16 @@ public static void printPlanCommandIngredients(
         System.out.println("Here are the ingredients you need to buy because your inventory is running low: ");
         missingIngredients.listIngredients();
     }
+
+    public static void printValidIngredientExample() {
+        System.out.println("Invalid Ingredient! Example of valid ingredient: i/Chicken,1,kg");
+    }
+
+    public static void printNegativeIngredientQuantity() {
```
Comment (charkty) [inline src/main/java/essenmakanan/ui/Ui.java:228]: Would it be better to name it printNegativeQuantityErrorMessage ?

File: src/test/java/essenmakanan/parser/IngredientParserTest.java
Comment (charkty) [inline src/test/java/essenmakanan/parser/IngredientParserTest.java:1]: I like your consideration of errors thrown!

**Review by charkty — APPROVED** [review]
Small changes to be made, overall very neat code!

**Review by StanleyW00 — APPROVED** [review]
