### PR TITLE
JU Test for start recipe and solve start recipe print statement bug

### LINKED ISSUE #173: Start command message output
**Note from the teaching team:** This bug was reported during the _Part II (Evaluating Documents)_ stage of the PE. **You may reject this bug if it is not related to the quality of documentation.**<hr>
I think the last line shouldn't be there since i alr have all the ingredients needed?

Also not sure if I'm supposed to do anything after starting the recipe or the start command is just to check if the recipe is ready

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: ryan1604/ped#5

### PR DESCRIPTION
**Pull request by charkty**
closes #173

### CODE REVIEW

File: src/main/java/essenmakanan/ingredient/Ingredient.java [hunk 1]
```diff
@@ -46,4 +46,12 @@ public void setUnit(IngredientUnit unit) {
...
         return  this.name + ": " + this.quantity + this.unit.getValue();
     }
+
+    public boolean equals(Ingredient i) {
+        boolean nameEqual = this.getName().equals(i.getName());
+        boolean quantityEqual = this.getQuantity().equals(i.getQuantity());
+        boolean unitEqual = this.getUnit().equals(i.getUnit());
+
+        return (nameEqual && quantityEqual && unitEqual);
+    }
```
Comment (kaijie0102) [inline src/main/java/essenmakanan/ingredient/Ingredient.java:56]: i like the overriding of equals, very useful

File: src/main/java/essenmakanan/ingredient/IngredientList.java [hunk 2]
```diff
@@ -123,4 +127,18 @@ public void listIngredients() {
             count++;
         }
     }
+
+    public boolean equals(IngredientList list) {
```
Comment (kaijie0102) [inline src/main/java/essenmakanan/ingredient/IngredientList.java:131]: same here, i like the equals overriding

File: src/main/java/essenmakanan/ui/Ui.java [hunk 3]
```diff
@@ -114,8 +114,8 @@ public static void printStartRecipeMessage(IngredientList missingIngredients,
                 diffUnitIngredients.listIngredients();
                 printNewLine();
             }
+            System.out.println("Start your recipe again after getting the above ingredients!");
```
Comment (kaijie0102) [inline src/main/java/essenmakanan/ui/Ui.java:117]: great that you only print message when needed

**Review by kaijie0102 — APPROVED** [review]
LGTM!
