### PR TITLE
Fix bugs and merge conflicts

### LINKED ISSUE #22: [Test] Create an Exception for EssenMakanan
Exceptions to the code will make our code more defensive

### LINKED ISSUE #32: [Enhancement] Create Recipe Parser

### PR DESCRIPTION
**Pull request by kaijie0102**
closes #22 and closes #32

### CODE REVIEW

File: src/test/java/essenmakanan/RecipeParserTest.java [hunk 1]
```diff
@@ -0,0 +1,31 @@
...
+    @BeforeEach
+    public void setUp() {
+        recipeParser = new RecipeParser();
+        recipes = new RecipeList();
+    }
+
+    @Test
+    public void parse_invalidCommand_exceptionThrown() {
+        try{
+            recipeParser.parseRecipeCommand(recipes, "invalid command", "invalid details");
```
Comment (charkty) [inline src/test/java/essenmakanan/RecipeParserTest.java:25]: Would it be better if you create 2 variables - invalidCommand and invalidDetails - and give them user like input to pass through the parser?

**Review by charkty — APPROVED** [review]
LGTM
