### PR TITLE
Fix bug where empty steps are not caught

### LINKED ISSUE #105: [Bug] Adding empty steps will throw an error
add r/bread s/ i/valid_ingredient

### PR DESCRIPTION
**Pull request by kaijie0102**
closes #105

### CODE REVIEW

File: src/main/java/essenmakanan/command/AddRecipeCommand.java [hunk 1]
```diff
@@ -47,11 +51,20 @@ public void addWithTitle() {
         Ui.printAddRecipeSuccess(recipeTitle);
     }
 
-    public void addWithTitleAndSteps() {
+    public void addWithTitleAndSteps() throws EssenFormatException {
         String[] allToAdd = toAdd.split("s/");
         String recipeTitle = RecipeParser.parseRecipeTitle(allToAdd[0].trim());
         String[] steps = new String[allToAdd.length - 1];
+        if (allToAdd.length==(1)){
```
Comment (StanleyW00) [inline src/main/java/essenmakanan/command/AddRecipeCommand.java:58]: I think that you should make it `allToAdd.length == (1)`

**Review by StanleyW00 — APPROVED** [review]
Overall, LGTM
