### PR TITLE
Fix storage bug

### LINKED ISSUE #169: [PE-D][Tester D] Storage - not updated when exiting without command exit
**Note from the teaching team:** This bug was reported during the _Part II (Evaluating Documents)_ stage of the PE. **You may reject this bug if it is not related to the quality of documentation.**<hr>
Error: When program is exited without using the command exit, the storage does not save the recipe and ingredients list. Program is not able to restore list when rebooted

Error: When program exited via exceptions

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: yeo-menghan/ped#13

### PR DESCRIPTION
**Pull request by StanleyW00**
Fix a bug where the storage will not save any data when exiting the application with `ctrl + c` and `NullPointerException` when creating a recipe / ingredient in first time session (when data folder and storage text files are created).

Fixes #169

### CODE REVIEW

File: src/main/java/essenmakanan/EssenMakanan.java [hunk 1]
```diff
@@ -41,21 +41,18 @@ public void run() {
             try {
                 command = parser.parseCommand(input, recipes, ingredients);
                 command.executeCommand();
+                ingredientStorage.saveData(ingredients.getIngredients());
+                recipeStorage.saveData(recipes.getRecipes());
```
Comment (kaijie0102) [inline src/main/java/essenmakanan/EssenMakanan.java:45]: great that now data is saved after every command!

**Review by kaijie0102 — APPROVED** [review]
LGTM!
